resolver: lts-11.9

packages:
- .
extra-deps:
- rio-0.1.2.0

docker:
  enable: true
image:
  container:
    base: "fpco/stack-build:lts-11.9"
    name: "ponkotuy/discord-vc-notification"
    entrypoints:
      - discord-vc-notification
